name: Build - Verify - Test
on:
  push:
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/workflows/pipeline.yaml'
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/workflows/pipeline.yaml'
  workflow_dispatch:
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  build:
    name: Build - Verify - Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 23
          distribution: 'zulu'
          cache: 'maven'

      - name: Build and Test
        id: maven-build
        run: mvn -B verify

      - name: Sonar Analysis
        if: success() || failure()
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: > 
          mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar 
          -Dsonar.projectKey=${{ github.repository_owner }}_templatepoo2026 
          -Dsonar.qualitygate.wait=true

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: JUnit Test Results
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: 'false'

      - name: Another Test Report
        uses: dorny/test-reporter@v2
        with:        
          name: JEST Tests                  # Name of the check run which will be created
          artifact: test-results            # artifact name
          path: '*.xml'                     # Path to test results (inside artifact .zip)
          reporter: jest-junit              # Format of test results
          fail-on-error: 'false'
        
      - name: Publish Code Coverage Report
        uses: madrapps/jacoco-report@v1.6
        if: success() || failure()
        with:
          paths: ${{ github.workspace }}/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
